language: python

sudo: required

services:
- docker

python:
- "2.7"

before_install:
# Update docker
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

# Update docker-compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64 > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

# Install pip dependencies - Might not be necessary....
install:
- pip install -r scraper/requirements.txt

# Run python tests
script:
- pytest -sv

# Remove pip log files to save space
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log

# Cache pip dependencies to save time between builds
cache:
  directories:
  - "$HOME/.cache/pip"

# Bundle application after tests have completed
after_success:
- docker pull wlabatey/python-build:2.7.14-slim
- /usr/local/bin/docker-compose -f $TRAVIS_BUILD_DIR/.build/docker-compose.yml up

# Deploy to AWS Lambda
deploy:
  - provider: lambda
    description: "Scrapy lambda function test deployment"
    function_name: scraper-test
    region: eu-west-2
    runtime: python2.7
    module_name: scrape
    handler_name: start_scrape
    zip: $TRAVIS_BUILD_DIR/dist/bundle/lambda-bundle.zip
    timeout: 300
    on:
      branch: master
    role:
      secure: "sInx0+BvZywQ2AW+pq9luA89UTPgTN6K9Qv0DcXGKlutEiQ7lh/G4oD6siviMeGj34YPO0by22PfCfZ3RQdtCudSMzwS4Ip9REbv5Qsd+joVAChLojuraj1FpLlmgQSmXlUazVR3SznwIVQMmAKDdl3QZ/zX5c4504XnfnHcnJOVBf78muYfUE49zI48l57N4zzzO80RrM4ecAXLzn2nKcy/v23B8pQJ3MEWwTNW12AeJCniFpGlLbjuKjD1QfoaoMDCF4Rd8cXAAdthTvKODXviwSLnTvYVPBB3iZ+Cva4reEi6jH8PnVaEhPV3m4w3ofIW0437MeR05IymcrePqDcV2GxuI2OOjH3evfuvh1YYeuNxc9bmCMwVFr7JqI6lho5kDyn7KaoMIjdH7PIPK3t01H8jtlCrDJRC6RA+gtgxcmUD95vSim7/LeZ1048MDZ0I11fx0wZn8u6vlVwP77VBcI/XULOXU0ehkd1jDD9VHd6D+9B3wK5X/n5WFphUEfHYNR8tQPFXtU4OXuOCLA524NXa65ENiUYe7aucgY+b/vvogigFB/4Fq7s2G3Q7zKU+dwyxT4eb5PWQmDWM1hI2DHBN3UmZwXgGxWpEbpame0EHKZcL1hy3ITUhGRQek23/SGxg2576a6zusyR6v/aUoD/eAIHFWhyOd8HT2Ew="
    access_key_id:
      secure: "PNeB41siiE1mBaF2gVcCbotZaEl1WR5q7AjUIg0/GCM3dFNJjigNmv9KBKStfLY3YYfEcXRa7h9UEzoEzkdiZlYZKj1/vlOUYEX+BvQzx2pjpTJ0ctu9AzaRAuDWqujNtIeo+gdEnwDABfNbeSgrhBrhIWSPr3Q0ZuDI2e6KNeCBebicRmUqKvG3OkRxodzE+9yXr5U/qTHyMkds7XA+ttJmTkGReynra5gz9RL06+7mgaCeLDQO5NyPye608eEOSduqlLaj8EMSEniGfdMJX4HbtGJX6Fd0+aS5oZw15LNK04FoEhGAkxz8Gut3RzxRmzO9YacXVo9tBBneiK/m7KmskvBnvROyutN7+fK76skspLOVPz0qEwwryJSFbpeayFGtKNg2TOByM5UakCTeo1LVYwd/2HDPyjnp+rWaEHwHF+Cr6W8O1lLoqB5eZusWtjz2oJT458XLZQPgu7DvXsoqBsYLf1ewYfPcFxVyCBjM/0h63iiQqZ66UP+fR4YU25FkFDAhB5Sd44Rw9kHEKjwLcKmElwUijad3WdKksYGHyJ5/u5DmRq99f0frU9N1/1wTKOIRF7RMP3GcqsLHTmBT7H163Vnkd17k+JGWi/MBXE8DuakghL6md+LoshvAvQTQweyBaM50ypWJLWkO+0YPj3z/4GIczvyaOhffKcQ="
    secret_access_key:
      secure: "VrNgFO0GFGDuVZxXONPf8JtHA2GK9PUKV0HFLx1pgEavEJQNATmIhwYQ2Z/imSdTkRqCT8XUh29mqrukM/xBiNkoKhp9gVKryB0IIOCcyzo1x5ZCpob5vvPOpzJWxLkq7HR88kn1QPbdqiQSpYzNhqX5ZPLC4T9x1Z2UKwUm2E9A09RNZdUz1jWbGFRkJoXajjc1pGnxcsBQpYJ5mZ68z7juDKPrh7ZJb4Vs3vszstXtxxyqL5gmnuOHuzRWN5qyXCxVk8+TszjyHTiP7GOg8H2f2toN2XJXzWPViz/7SomZXvMiW0QRGtBJwJDLrROGsV2PBN3FqXCclRvNd9L2sKixiWhX3xeFzUK9X/KLJ60g2NK6eW9AlhfBfLF3Xzg4IaiasGYw7XyAjJ6hTLZalXBOUFP07skPNM0p1qvDF15YnB+zyn1dwCqnDwF7SWpmQXFbT5qXQnslQfEoQOE0GHhCs9Stn2XUZmBo5NrWvlKfdSWUGqTfQSxqL5/2gtkE8QpRdF6UWEIM6vHJLFzsorKx7KD7T92MJXh/8SpN26sMe4d1Yr9Z6mCfvi9aJ4TwNBmTYAWaqqEDycUso7OIobZHhaLO6Twwoub3megEqIeQWYpVnHeO5gGkGjSsUBA8x3JoHwdTVdZ0rixkGHyBoCK+9Dko1i3+IzTrZpHlmRo="

  - provider: s3
    bucket:
      secure: "tjqu2U86cjbmU4HYeGqbK+3a0eks4v3AAdT3/Fz48URFx8/O7PsgTdB3X3ZWcT6v3FM4GYJdkiu4xCG4JG6mKOrRDow1QFYxC8DB0xXq0OnMSi+uGNVc9OOYVOXkKHck7+UHBEnLuLJ46aMf4CHTuQ02xbpjzhaON1bGM/YGGkVSTxCBohLil5sYMXQBW9sP6tO18h8JQKSyv0ef5FK8++PnpZc4McTmASKoNZ1zrkZs6SnfKI/cbOjWtfXpP48Rzr+gJjFE3+eKKuUdgnFYygo4td8/l6R1h/T4MEqxMhc0yzqOdU/yctX056Kx5NL7YSSmkn2fCzG+28nOBJnF9BaHRtuqIq7fqrKFvuK2mr324v58Jlr5YPMXnheHE4pduZVnt8S7/E3iemt0EXoxlw2R5thuwuLF5XPVZv6Y+OPKrRPdslAHHa3+P2NGQPgZpypAfgrpHOA8dVpfMJhFlRFuDDvu2QrLITZtnWf9LASejcgmvtVjDgA0P5s0SJAnBGqU1mR+AhQ/MrlCdW7foPInAXPL0vSfHUDQWFOC7k2Cwvqp2VwpcgGT2RHTj2C5n6z/5wtM6psrDajz0pYEalWpjNWV3oOy5n8AAfqhXyuFnI2VblFs/UZI0cEDfgqgh/T0Tr3yQSLaihmY66xRO/W4tdErRsXxwhNi9uUTQnA="
    region: eu-west-2
    local_dir: $TRAVIS_BUILD_DIR/site
    skip_cleanup: true
    acl: public_read
    access_key_id:
      secure: "PNeB41siiE1mBaF2gVcCbotZaEl1WR5q7AjUIg0/GCM3dFNJjigNmv9KBKStfLY3YYfEcXRa7h9UEzoEzkdiZlYZKj1/vlOUYEX+BvQzx2pjpTJ0ctu9AzaRAuDWqujNtIeo+gdEnwDABfNbeSgrhBrhIWSPr3Q0ZuDI2e6KNeCBebicRmUqKvG3OkRxodzE+9yXr5U/qTHyMkds7XA+ttJmTkGReynra5gz9RL06+7mgaCeLDQO5NyPye608eEOSduqlLaj8EMSEniGfdMJX4HbtGJX6Fd0+aS5oZw15LNK04FoEhGAkxz8Gut3RzxRmzO9YacXVo9tBBneiK/m7KmskvBnvROyutN7+fK76skspLOVPz0qEwwryJSFbpeayFGtKNg2TOByM5UakCTeo1LVYwd/2HDPyjnp+rWaEHwHF+Cr6W8O1lLoqB5eZusWtjz2oJT458XLZQPgu7DvXsoqBsYLf1ewYfPcFxVyCBjM/0h63iiQqZ66UP+fR4YU25FkFDAhB5Sd44Rw9kHEKjwLcKmElwUijad3WdKksYGHyJ5/u5DmRq99f0frU9N1/1wTKOIRF7RMP3GcqsLHTmBT7H163Vnkd17k+JGWi/MBXE8DuakghL6md+LoshvAvQTQweyBaM50ypWJLWkO+0YPj3z/4GIczvyaOhffKcQ="
    secret_access_key:
      secure: "VrNgFO0GFGDuVZxXONPf8JtHA2GK9PUKV0HFLx1pgEavEJQNATmIhwYQ2Z/imSdTkRqCT8XUh29mqrukM/xBiNkoKhp9gVKryB0IIOCcyzo1x5ZCpob5vvPOpzJWxLkq7HR88kn1QPbdqiQSpYzNhqX5ZPLC4T9x1Z2UKwUm2E9A09RNZdUz1jWbGFRkJoXajjc1pGnxcsBQpYJ5mZ68z7juDKPrh7ZJb4Vs3vszstXtxxyqL5gmnuOHuzRWN5qyXCxVk8+TszjyHTiP7GOg8H2f2toN2XJXzWPViz/7SomZXvMiW0QRGtBJwJDLrROGsV2PBN3FqXCclRvNd9L2sKixiWhX3xeFzUK9X/KLJ60g2NK6eW9AlhfBfLF3Xzg4IaiasGYw7XyAjJ6hTLZalXBOUFP07skPNM0p1qvDF15YnB+zyn1dwCqnDwF7SWpmQXFbT5qXQnslQfEoQOE0GHhCs9Stn2XUZmBo5NrWvlKfdSWUGqTfQSxqL5/2gtkE8QpRdF6UWEIM6vHJLFzsorKx7KD7T92MJXh/8SpN26sMe4d1Yr9Z6mCfvi9aJ4TwNBmTYAWaqqEDycUso7OIobZHhaLO6Twwoub3megEqIeQWYpVnHeO5gGkGjSsUBA8x3JoHwdTVdZ0rixkGHyBoCK+9Dko1i3+IzTrZpHlmRo="

git:
  depth: 3

branches:
  only:
  - master
  - dev

# Send notifications to IRC channel
notifications:
  irc:
    on_success: always
    on_failure: always
    use_notice: true
    channels:
      secure: "tpotWC8VNWOtgVpZ1vKiwuNUjqbcvwx6jjXju06SRyMz50P1G6CwwUGQEaKellaLLlIliE+D/pnQMkkPAqjV4rXJgJvrPcHB6chB1/Fvm1lhic/lG5H3Od3uYHfGR0o8MTxcKQA93SIhSs0iVjnzy/cpETEXjpsQ2HVwOMJSwsm+VkfHiozJ7oJhtsdBKy4IwnE5moR36Mgc66BdauuV+V77QHZKdJsdM/hpz6L6rZ0FmZkj4gb70ZGz2N0hnrsPQoxrrsAhdazsYgiGRQeRcVOPSK2fhb/RFDrbdN9brOS4XkU8UIDjyGxXiYExcdrmSDHC8zihbwgpwMI4sjw5+TQ/eiyFhq2OkHtBMjPLDE+3cemU+0dzJlH6opcf1aR5f/pqLmbmXe/Masf/TrB503A9+g1JxJ6IrdXNTzBagb3+fq00K3dWcOjBJD/SXFs6Us8BzfMgR0f1M6p59Dr9JWxqrveFMUvvYeurioed/x3c5D/1C1ccD/YnNkb1IOJvHWoa1g2KYISq6tkT9Urs2G6WE/0aQ7ucdfshEXnYUuL5qGcpQSecaBXKCxLxQeeVqf60lUzzQc2w43hBz5vf3cjVnl7JfkZtmRXae+ZA9YDCnnwGRDKdUxTwbxB88/rQ12p5bLrd2pQVflHzGXqWMa+ZKpLDlh7zgIbzJjxKGg4="
