language: python
python:
- 3.6
install:
- pip install -r scraper/requirements.txt
script:
- pytest -sv
notifications:
  irc:
    on_success: always
    on_failure: always
    use_notice: true
    channels:
      secure: tpotWC8VNWOtgVpZ1vKiwuNUjqbcvwx6jjXju06SRyMz50P1G6CwwUGQEaKellaLLlIliE+D/pnQMkkPAqjV4rXJgJvrPcHB6chB1/Fvm1lhic/lG5H3Od3uYHfGR0o8MTxcKQA93SIhSs0iVjnzy/cpETEXjpsQ2HVwOMJSwsm+VkfHiozJ7oJhtsdBKy4IwnE5moR36Mgc66BdauuV+V77QHZKdJsdM/hpz6L6rZ0FmZkj4gb70ZGz2N0hnrsPQoxrrsAhdazsYgiGRQeRcVOPSK2fhb/RFDrbdN9brOS4XkU8UIDjyGxXiYExcdrmSDHC8zihbwgpwMI4sjw5+TQ/eiyFhq2OkHtBMjPLDE+3cemU+0dzJlH6opcf1aR5f/pqLmbmXe/Masf/TrB503A9+g1JxJ6IrdXNTzBagb3+fq00K3dWcOjBJD/SXFs6Us8BzfMgR0f1M6p59Dr9JWxqrveFMUvvYeurioed/x3c5D/1C1ccD/YnNkb1IOJvHWoa1g2KYISq6tkT9Urs2G6WE/0aQ7ucdfshEXnYUuL5qGcpQSecaBXKCxLxQeeVqf60lUzzQc2w43hBz5vf3cjVnl7JfkZtmRXae+ZA9YDCnnwGRDKdUxTwbxB88/rQ12p5bLrd2pQVflHzGXqWMa+ZKpLDlh7zgIbzJjxKGg4=
