version: "3.3"
services:
  python-build:
    build: 
      context: .
      image: wlabatey/python-build:2.7.14-slim
      cache_from:
        - python:2.7.14-slim
        - wlabatey/python-build:2.7.14-slim
    volumes:
      - type: bind
        source: ..
        target: /usr/src/app
